server:
  # Хост на якому працює Lavalink
  host: localhost  # або "localhost", якщо працює на вашій локальній машині
  
  # Порт, на якому Lavalink буде слухати запити
  port: 2333  # Ви можете змінити цей порт за бажанням
  
  # Пароль для підключення до Lavalink
  password: "youshallnotpass"  # Це пароль, який потрібно використовувати в коді бота
  
  # Налаштування безпеки
  secure: false  # false, якщо не використовуєте SSL
